<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Apache.DataFusion" Version="0.1.8" />
      <PackageReference Include="Apache.DataFusion.Native.win-x64" Version="0.1.8" />
      <PackageReference Include="Apache.DataFusion.TableProviders.ClickHouse" Version="0.1.8" />
      <PackageReference Include="Apache.DataFusion.TableProviders.MongoDB" Version="0.1.8" />
      <PackageReference Include="Apache.DataFusion.TableProviders.MySql" Version="0.1.8" />
      <PackageReference Include="Apache.DataFusion.TableProviders.PostgreSql" Version="0.1.8" />
      <PackageReference Include="Apache.DataFusion.TableProviders.Sqlite" Version="0.1.8" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Nexova.Core\Nexova.Core.csproj" />
    </ItemGroup>

</Project>
